In [1]:
import pandas as pd

In [15]:
file_to_load = "indep.csv"

In [4]:
head_to_load = "pas2_header_file.csv"

In [8]:
df = pd.read_csv(head_to_load)

In [81]:
df_column_names = list(df.columns)
df_column_names

['CMTE_ID',
 'AMNDT_IND',
 'RPT_TP',
 'TRANSACTION_PGI',
 'IMAGE_NUM',
 'TRANSACTION_TP',
 'ENTITY_TP',
 'NAME',
 'CITY',
 'STATE',
 'ZIP_CODE',
 'EMPLOYER',
 'OCCUPATION',
 'TRANSACTION_DT',
 'TRANSACTION_AMT',
 'OTHER_ID',
 'CAND_ID',
 'TRAN_ID',
 'FILE_NUM',
 'MEMO_CD',
 'MEMO_TEXT',
 'SUB_ID']

In [82]:
df2 = pd.read_csv(file_to_load, header = None)

In [84]:
df2.head()

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,CAND_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00567180,T,TER,P,2.020000e+17,24K,PAC,TED YOHO FOR CONGRESS,GAINESVILLE,FL,...,NaN,1082019.0,1880,C00494583,H2FL06109,SB23.4447,1303604,NaN,NaN,4.020000e+18
1,C00104885,A,TER,P,2.020000e+17,24K,CCM,FRIENDS OF JIM CLYBURN,COLUMBIA,SC,...,NaN,1072019.0,470,C00255562,H2SC02042,SB23.17755,1307636,NaN,NaN,4.020000e+18
2,C00104885,A,TER,G,2.020000e+17,24K,CCM,TEAM GRAHAM INC,COLUMBIA,SC,...,NaN,12202018.0,3000,C00458828,H4SC03087,SB23.17757,1307636,NaN,NaN,4.020000e+18
3,C00104885,A,TER,P,2.020000e+17,24K,CCM,TIM SCOTT FOR SENATE,CHARLESTON,SC,...,NaN,12202018.0,1000,C00540302,H0SC01279,SB23.17756,1307636,NaN,NaN,4.020000e+18
4,C00688408,T,TER,G2018,2.020000e+17,24E,ORG,JACKSON ADVOCATE,JACKSON,MS,...,NaN,12122018.0,1000,S8MS00287,S8MS00287,SE.4233,1310906,NaN,NaN,4.020000e+18

In [83]:
df2.columns = df_column_names

In [80]:
df2

,CMTE_ID,AMNDT_IND,RPT_TP,TRANSACTION_PGI,IMAGE_NUM,TRANSACTION_TP,ENTITY_TP,NAME,CITY,STATE,...,OCCUPATION,TRANSACTION_DT,TRANSACTION_AMT,OTHER_ID,CAND_ID,TRAN_ID,FILE_NUM,MEMO_CD,MEMO_TEXT,SUB_ID
0,C00567180,T,TER,P,2.020000e+17,24K,PAC,TED YOHO FOR CONGRESS,GAINESVILLE,FL,...,NaN,1082019.0,1880,C00494583,H2FL06109,SB23.4447,1303604,NaN,NaN,4.020000e+18
1,C00104885,A,TER,P,2.020000e+17,24K,CCM,FRIENDS OF JIM CLYBURN,COLUMBIA,SC,...,NaN,1072019.0,470,C00255562,H2SC02042,SB23.17755,1307636,NaN,NaN,4.020000e+18
2,C00104885,A,TER,G,2.020000e+17,24K,CCM,TEAM GRAHAM INC,COLUMBIA,SC,...,NaN,12202018.0,3000,C00458828,H4SC03087,SB23.17757,1307636,NaN,NaN,4.020000e+18
3,C00104885,A,TER,P,2.020000e+17,24K,CCM,TIM SCOTT FOR SENATE,CHARLESTON,SC,...,NaN,12202018.0,1000,C00540302,H0SC01279,SB23.17756,1307636,NaN,NaN,4.020000e+18
4,C00688408,T,TER,G2018,2.020000e+17,24E,ORG,JACKSON ADVOCATE,JACKSON,MS,...,NaN,12122018.0,1000,S8MS00287,S8MS00287,SE.4233,1310906,NaN,NaN,4.020000e+18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89115,C00104299,N,M9,P,2.020000e+17,24K,CCM,WENSTRUP FOR CONGRESS,CINCINNATI,OH,...,NaN,8022019.0,2000,C00497818,H2OH02085,D46E3F9F66FA54354ED,1353190,NaN,NaN,4.090000e+18
89116,C00171843,N,M9,P,2.020000e+17,24K,CCM,MEADOWS FOR CONGRESS,HENDERSONVILLE,NC,...,NaN,8272019.0,-1000,C00503094,H2NC11080,10316943,1353417,NaN,VOIDED CK FROM 5/8/2019,4.090000e+18
89117,C00171843,N,M9,P,2.020000e+17,24K,CCM,REED COMMITTEE; THE,CRANSTON,RI,...,NaN,8212019.0,1000,C00238907,S6RI00163,10300503,1353417,NaN,CONTRIBUTION,4.090000e+18
89118,C00171843,N,M9,P,2.020000e+17,24K,CCM,"KUSTER FOR CONGRESS, INC",CONCORD,NH,...,NaN,8212019.0,1000,C00462861,H0NH02181,10300504,1353417,NaN,CONTRIBUTION,4.090000e+18
89119,C00171843,N,M9,P,2.020000e+17,24K,CCM,DIANA DEGETTE FOR CONGRESS,DENVER,CO,...,NaN,8212019.0,2500,C00311639,H6CO01141,10300505,1353417,NaN,CONTRIBUTION,4.090000e+18